server:
  port: 9194
  servlet:
    context-path: /notification
spring:
  config:
    import: "secrets.yml"
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification-service
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer