server:
  port: 9194
  servlet:
    context-path: /notification

spring:
  config:
    import: "secrets.yml"
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification-service
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  notification:
    email:
      brevo-url: https://api.brevo.com

# Logging Configuration
logging:
  file:
    name: record-management-service.log
    max-size: 10MB
    max-history: 10
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

# Sonar Configuration
sonar:
  projectKey: record-management-service
  projectName: Hospital Management project
  host:
    url: http://localhost:9000