server:
  port: 9194
  servlet:
    context-path: /notification
spring:
  config:
    import: "secrets.yml"
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification-service